title: jieyuanzhi's Homepage
page-top-title: jieyuanzhi
top-section-bg-text: Open Source Software Design and Development
home-subtitle: jieyuanzhi&ensp;|&ensp;揭远志
copyright-text: '&copy; jieyuanzhi 2023-2024. All Rights Reserved.'
